version: 2.1

orbs:
  windows: circleci/windows@5.0

commands:
  build_and_test:
    description: "Configure, build and test with cmake"
    parameters:
      cpp_compiler:
        type: "string"
      c_compiler:
        type: "string"
      build_type:
        type: "enum"
        enum: [ "Release", "Debug", "RelWithDebInfo" ]

    steps:
      # - checkout
      - run:
          command: >
            cmake -B build 
            -DCMAKE_CXX_COMPILER=<<parameters.cpp_compiler>>
            -DCMAKE_C_COMPILER=<<parameters.c_compiler>>
            -DCMAKE_BUILD_TYPE=<<parameters.build_type>>
            -G Ninja
            -S .
      - run:
          command: cmake --build build --config <<parameters.build_type>>
      - run:
          command: >
            ctest --build-config <<parameters.build_type>>
            --output-on-failure
            --output-junit test-results.xml
            --test-dir build
      - store_test_results:
          path: build/test-results.xml



jobs:
  linux-gcc13:
    parameters:
      build_type:
        type: "enum"
        enum: [ "Release", "Debug", "RelWithDebInfo" ]
      res_type:
        type: "enum"
        enum: ["small", "arm.medium"]
    docker:
      - image: rsentinel/gcc-builder:latest
    resource_class: <<parameters.res_type>>
    steps:
      - checkout
      - build_and_test:
          cpp_compiler: "g++"
          c_compiler: "gcc"
          build_type: <<parameters.build_type>>

  msvc-win64:
    description: "Windows MSVC c++20 VS2022 x64 Build"
    parameters:
      build_type:
        type: "enum"
        enum: [ "Release", "Debug", "RelWithDebInfo" ]
    executor:
      name: windows/default
      size: medium
    steps:
      - checkout
      - run: systeminfo
      - run: choco install -y ninja cmake.install --installargs 'ADD_CMAKE_TO_PATH=User'
      - run:
          command: .\.circleci\build.bat  <<parameters.build_type>>
          shell: cmd.exe
      - store_test_results:
          path: build/test-results.xml


  macos-xcode:
    description: "Windows MSVC c++20 VS2022 x64 Build"
    parameters:
      build_type:
        type: "enum"
        enum: [ "Release", "Debug", "RelWithDebInfo" ]
      res_type:
        type: "enum"
        enum: ["macos.x86.medium.gen2", "macos.m1.medium.gen1"]
      xcode_ver:
        type: "enum"
        enum: [ "15.4.0", "15.3.0" ]
    macos:
      xcode: <<parameters.xcode_ver>>
    resource_class: <<parameters.res_type>>
    steps:
      - run: brew install cmake
      - run: brew install ninja
      - checkout
      - build_and_test:
          cpp_compiler: "clang++"
          c_compiler: "clang"
          build_type: <<parameters.build_type>>

workflows:
  build_test:
    jobs:
      - linux-gcc13:
          matrix:
            parameters:
              build_type: [ "Release", "Debug", "RelWithDebInfo" ]
              res_type: ["small", "arm.medium"]

      - msvc-win64:
          matrix:
            parameters:
              build_type: [ "Release", "Debug", "RelWithDebInfo" ]

      - macos-xcode:
          matrix:
            parameters:
              build_type: [ "Release", "Debug", "RelWithDebInfo" ]
              res_type: ["macos.x86.medium.gen2"]
              xcode_ver: ["15.3.0"]

#    macos:
#      xcode: 15.3.0