version: 2.1

commands:
  build_and_test:
    description: "Configure, build and test with cmake"
    parameters:
      cpp_compiler:
        type: "string"
      c_compiler:
        type: "string"
      build_type:
        type: "enum"
        enum: [ "Release", "Debug", "RelWithDebInfo" ]

    steps:
      # - checkout
      - run:
          command: >
            cmake -B build 
            -DCMAKE_CXX_COMPILER=<<parameters.cpp_compiler>>
            -DCMAKE_C_COMPILER=<<parameters.c_compiler>>
            -DCMAKE_BUILD_TYPE=<<parameters.build_type>>
            -G Ninja
            -S .
      - run:
          command: cmake --build build --config <<parameters.build_type>>
      - run:
          command: >
            ctest --build-config <<parameters.build_type>>
            --output-on-failure
            --output-junit test-results.xml
            --test-dir build
      - store_test_results:
          path: build/test-results.xml



jobs:
  linux-gcc13:
    parameters:
      build_type:
        type: "enum"
        enum: [ "Release", "Debug", "RelWithDebInfo" ]
    docker:
      - image: rsentinel/gcc-builder:latest
    resource_class: small
    steps:
      - checkout
      - build_and_test:
          cpp_compiler: "g++"
          c_compiler: "gcc"
          build_type: <<parameters.build_type>>


workflows:
  build_test:
    jobs:
      - linux-gcc13:
          matrix:
            parameters:
              build_type: [ "Release", "Debug", "RelWithDebInfo" ]
#    macos:
#      xcode: 15.3.0