version: 2.1

commands:
  setup_gcc12:
    steps:
      - run:
          name: "Download dependencies"
          command: |
            sudo apt-get update
            sudo apt-get install -y ninja-build cmake g++-12 libstdc++-12-dev
  setup_debian:
    steps:
      - run:
          name: "Download dependencies"
          command: |
            apt-get update
            apt-get install -y ninja-build cmake
      - run:
          name: "Create user"
          command: |
            useradd -m -U circleci
            su -l circleci
            cd /home/circleci
            mkdir project
            cd project

  build_and_test:
    description: "Configure, build and test with cmake"
    parameters:
      cpp_compiler:
        type: "string"
      c_compiler:
        type: "string"
      build_type:
        type: "enum"
        enum: [ "Release", "Debug", "RelWithDebInfo" ]

    steps:
      # - checkout
      - run:
          command: >
            cmake -B build 
            -DCMAKE_CXX_COMPILER=<<parameters.cpp_compiler>>
            -DCMAKE_C_COMPILER=<<parameters.c_compiler>>
            -DCMAKE_BUILD_TYPE=<<parameters.build_type>>
            -G Ninja
            -S .
      - run:
          command: cmake --build build --config <<parameters.build_type>>
      - run:
          command: >
            ctest --build-config <<parameters.build_type>>
            --output-on-failure
            --output-junit test-results.xml
            --test-dir build
      - store_test_results:
          path: build/test-results.xml

jobs:
  linux-gcc13-debug:
    docker:
      - image: rsentinel/gcc-builder:v0
    resource_class: small
    steps:
      - checkout
      - build_and_test:
          cpp_compiler: "g++"
          c_compiler: "gcc"
          build_type: "Debug"

  linux-gcc12-release:
    docker:
      - image: cimg/base:current-22.04
    resource_class: small
    steps:
      - setup_gcc12
      - checkout
      - build_and_test:
          cpp_compiler: "g++-12"
          c_compiler: "gcc-12"
          build_type: "Release"


workflows:
  build_test:
    jobs:
      - linux-gcc13-debug
      - linux-gcc12-release
#    macos:
#      xcode: 15.3.0